---
title: "语言的国家治理功能与路径研究"
subtitle: "（工作论文，未经作者允许请勿转载或收入论文集）"
author:
- 胡悦
- 朱萌^[胡悦，清华大学政治学系副教授；朱萌，通讯作者，清华大学政治学系硕士研究生。本文为国家自然科学基金委面上项目（72374116）“经济不平等的经济与治理认知塑造机制与行为政策引导策略研究”研究成果。]

output:
  bookdown::word_document2:
    keep_md: yes
    number_section: false
    reference_docx: template_cn.docx
fontsize: 12 pt
geometry: margin=1in
bibliography: language_governance.bib
csl: "american-political-science-review.csl"
link-citations: true
colorlinks: false
editor_options: 
  markdown: 
    wrap: sentence
always_allow_html: true

abstract: |

 **摘要**：语言治理国家治理的重要组成部分和战略支撑力量，是维护政治与文化统一、增强国家认同、保障社会稳定的必要条件。
 然而，对于认知语言治理的理论架构尚未搭建完成。
 为实现对语言治理在国家治理维度和上的系统性和全面性认知，本文运用系统功能类型学方法，梳理语言在国家、群体和个体三个层面的贯通治理功能，阐明语言治理在现代化治理中的基础性和根本性作用。
 进而，在综合前沿政治语言学研究成果基础上，提出语言治理提升国家治理能力的三条实践路径。
 最后，针对新时期城市治理、共同富裕、新媒体治理等核心治理领域，讨论语言治理在解决现实治理挑战、推动治理能力现代化上的重要功用，并为新时期语言治理方向与策略提出建议。
 本文总结，语言治理事关国家政治安全和经济社会发展，更可保障国家政策得以顺畅运行、有效运行、高效运行、合法运行的治理手段。
 
 **关键词**：语言治理；国家治理；政治安全；。
---

# 引言

语言，是人类的根本特征，对人类社会的文化走向、制度设置、价值塑造都具有关键性作用[@MaKeSiEnGeSi1961;@Mead2012]。
从国家治理角度，语言从古至今都是政治生活的核心载体和推行政策的重要途径[@WangChunHui2020a]。
政府通过使用特定词汇表达和理论解释，将治国理念和施政方针进行阐释和传播，服务于政治稳定、经济发展和文化传承，最终达到维护社会稳定、促进现代化发展的最终目的[@MillerRose1990]。
在总体国家安全观的指引下，对于语言治理意涵的理解，更应上升到国家政治安全高度。
语言态度、语言身份、语言意识形态、以及政治话语等方面，都民族建构和国家形成息息相关，是维护政治统一、增强国家认同、保障社会稳定的必要条件[@LiangXiaoBoYangXiaoQing2022]。

然而，目前相关理论研究中对语言治理认知多停留工具层次，将语言视为规范社会结构和族群结构、推行规范教育的一种公共政策手段[XXXX]。
实证研究也多局限于对语言在流动人口、民族/国家身份等方面作用的探索[@WuXiaoJun2013;@DaiManChunZhuNingYan2011;@LiuHuaXiaYuanQingHuan2017]。
对于语言治理功能系统理解上的缺失与当前社会科学发展和国家推进治理能力现代化实践已逐渐形成张力：

从研究发展德角度，随着政治语言学、社会语言学、语言心理学等交叉学科研究的开展，我们已经获得越来越多的证据昭示语言在保证国家财政和经济生活稳步运行、国家形象塑造与文化安全等方面的基础性角色[@WangChunHui2019a;@Hu2020b]，以及在社会治理中的黏合剂和稳定器的作用[@YangBaoYan2014]。
实证研究的多面突破，进一步呼唤系统框架对这些观察发现内部关联的总结和阐释，进而形成理论认知，推进对于国家治理体系和治理能力现代化的多维度理解。

而从治理实践角度，深化改革的总任务和推进治理能力现代化的总目标都对政府治理的综合性和有效性提出了更高的要求[@LiYuMing2018]。
如何精准传达政策信息和把握政治方向，如何掌握网络话语权和实现群体动员，如何搭建高效政民信息互通和意见互动，都是新时期政府治理能力提升的重要内容，而无一不与语言使用息息相关。
2016年，国家语言治理被写入《国家语言文字事业“十三五”发展规划》。
规划明确提出，要实现语言治理与国家治理相适应。
2020年10月，我国第一次全国语言文字会议上提出要“推进语言文字治理体系和治理能力现代化”。
对于语言治理功能的全面认识，是这些目标实现的基础性条件。


面对理论发展和治理实践德双重需求，笔者采用系统功能类型学（systemic functional typology）视角，在梳理政治语言学前沿成果基础上，就语言在国家、群体和个体层次上的治理定位和功能进行系统性讨论，揭示语言对增进国家认同、促进群体团结、稳定社会政治心态德核心作用。
基于语言治理特性，本文总结语言治理提高国家治理的三条主要实现途径：规范推行、群体关系和个体治理，并结合新时期发展需求和挑战，阐述语言治理对我国城市治理、乡村振兴与共同富裕、新媒体治理等重要治理面向的实践意义，为进一步地实现“共建、共治、共享”的社会良性发展和制度建构提供借鉴思路。


# 语言的治理定位与功能

语言作为人类社会最重要的交际与思维符号体系，是传递信息与价值，交流思想与情感的工具，是组织社会、承载文化、提升认知、发展经济的有效途径。
不同视角、不同学科对其功能与作用给予了各种不同阐释：
经济学家将语言技能视作一种经济优势和资本[@LiangEtAl2018]；
社会学家强调语言的个人性与社会性[@Mead2012]；
政治学家则认为语言与国家构建息息相关[@Benedict2005]。
系统功能类型学为综合这三种社会科学主流学科观点，形成对于语言治理功能系统认知提供了认识论框架。

系统功能类型学原为一种系统功能语言学方法，旨在揭示语言在社会运行上的功能性特点[@HallidayEtAl1964;@Cummings2019;@GuoWen2007]。
笔者将这种视角与加强国家治理和维护国家安全的政治需求相结合，提出语言规划作为一种公共制度体系和公共政策手段对国家治理、群体治理和个体治理三个层次上的功能特点：

## 语言的国家治理功能

国家治理是国家政权的所有者、管理者和利益相关者等多元行动者在一个国家范围内对社会公共事务的合作管理，以维护公共秩序、增进国家利益、实现社会团结[@HeZengKe2014]。
语言则是影响国家治理有效性和执政合法性的关键性因素：政治生活中，国家通过合理安排语言政治权力，实现语言政治权力的善治，因此语言治理必须体现政治的立场和政治的高度 [@Hu2020b]。
具体而言，语言的全国治理功能主要体现在国家通用语和语言结构设定两个方面：

国家通用语言对于加强国家整合和塑造民族认同具有重要作用。 国家通用语言的掌握消除了各地区和各民族因语言差异带来的不安，消弭了地域保护主义，有助于构建统一的民族或国族身份和想象的共同体，从而维护了国家统一和民族团结[@ZhangWeiGuo2020;@HuangShaoAnWangLuCong2020]。
从秦始皇统一文字到孝文帝“断北语，从正音”，从明代《洪武正韵》到清代“以官音统一天下之语言”、从民国的“国语运动”到新中国推广普通话、修订汉语拼音等。
波澜壮阔、传承延绵的中华语言治理历史无不表明了语言是构建国家认同的重要对象和构成要素。 

语言治理需要处理的另一个重要面向是语言结构，即国家通用语与地方语言的关系问题。
方言是历史和地理因素共同作用的结果，具有地区交流和文化认同功能。
从治理角度，方言和民族语言有助于加强政策宣导效果，提高官民沟通效率。 从语言功能的角度来看，交际便利与否是语言使用的关键因素，国家通用语言使用的便利性对地方治理和基层治理来说很多时候会低于方言和民族语言[@LiuHuaXiaYuanQingHuan2017]。
单以汉语为例，有官话、晋语、吴语、闽语、粤语、客家话、赣语、湘语、徽语、平话和土话等十大方言，还可进一步细分为97个方言片，101个方言小片。 很多方言内部可以达成高校沟通，但方言之间却无法实现沟通。
最近研究表明，普通百姓在日常生活中仍较多使用方言交流，采取本地人用本地话讲本地事的形式，更有利于政策的传达和民众的理解 [@HuPizzi2022]。
尤其面对我国内部语言方言差异巨大的客观事实，语言沟通将阻碍了地方政府开展工作，进而引发的语言服务需求已成为亟需解决的问题。 
只有既推广国家通用语，又在治理实践中灵活运用方言，才能实现属地与跨地域治理的双高效。

总之，国家通用语作为国家记忆和文化的主要载体一直以来受到各国政策制定者的关注和争相推广。
国族的共同记忆、历史传统、文化价值等要素的维系和传递，都需要统一的民族语言作为基础[@Anthony2002]。
与此同时，方言和民族语言作为一种语言力量，是一把双刃剑。既可以有效传达政治信息和推动政策目标的实施，提高地方治理绩效；也可以被用来实施民族分裂和种族异化、谋取不正当利益，成为民族运动领导层得心应手的政治工具[@DaiManChunZhuNingYan2011]。


## 语言的群体治理功能

语言的国家治理主要从宏观角度出发，着力于塑造政治秩序、提升治理治理效率。
在中观层面，语言治理同样具有群体治理功能。
群体治理强调民众的自我管理能力，指在没有政府的参与下，通过自我协作、信任关系、社会交往以及非正式协议等自治手段，通过自下而上的权力运作方式来管理社会团体和社会组织[@Ostrom2015]。
社会认同理论（Social Identity Theory）提出，个体通过人际互动塑造群体利益（shared interests），而语言对于满足人际交往和社会互动的紧迫需求，在更广泛意义上团结松散民众，形成集体凝聚力具有重要作用[@HenriTajfelJohnTurner2004]。

语言是厘定文化群体（cultural communities）边界的核心指标，因语言而划定的群体边界，促使人们在心理和文化上对“我者”与“他者”做出判断。人类社会自古以来最简单也是最有效表明自己身份和判断他人身份的手段就是语言[@WangKeFei2011]，人们在听到某种特定语言类型后，会对语言使用者产生一些直观感受和印象[@LiuHong1993]，从而对不同种类的语言使用人群产生不同情感和态度差异。
基于对不同个体语言能力差异的研究，@LiuHuaXiaYuanQingHuan2017  指出，语言差异会影响群体之间的相互认同，甚至会形成心理隔阂，从而造成社会认知和社会判断的固化。
国外移民研究也表明，语言是社会融合的前提条件，是正式进入移民社会的必要条件。持有不同语言的移民会遭遇来自主流社会的敌意和排斥，因而由自身母语方言到当地方言的转变被看作是移民文化适应和社会融入的关键标志[@RendallEtAl2010;@DustmannFabbri2003]。在这一意义上，对通用语和流行语的掌握程度也就塑造了社会个体对于主流社会的融入程度[@VroomeEtAl2013]。 

## 语言的个体治理功能

@Giddens2000 认为，个体治理包含“解放政治”和“生活政治”的双元混合，前者强调对社会地位和社会权利的争取，后者则侧重于对社会认同和自我实现的追求。
当前，中国社会结构发生巨大变革，个体的话语表达、经济活动、自我组织和自我管理等空间被逐渐释放出来，个体的自主意识、权利意识以及竞争意识也日益增强。这一改变导致传统社会对个体治理的运作路径面临极大挑战，以个体利益、个体成就为导向的价值追求促使中国传统社会一直以来的集体化治理模式和治理框架逐步瓦解[@HongBo2018]。
然而，语言作为重要的资本符号，能够伴随文化资本、经济资本和社会资本参与到资本转换中，并进一步对个体能力和个体认知产生重要影响，由此实现个体治理[@YingJiZhuoMa2018]。

就个体能力而言，语言作为人类经济活动的工具，在信息传递上具有价值、效用、成本和收益等经济特性。
一种语言掌握越好，信息沟通成本越低，信息收益越大，个体就越容易了解与掌握相关的政治、经济、法律等社会生活中的知识和惯例[@ZhangWeiGuo2011]。
社会语言学表明，掌握一门语言能够有效提高个体的信息获取能力，进而享有更多的公共资源和发展机会。 实证研究也显示，语言水平相对较高的人群由于交流障碍更少，拥有更好表现自身能力的交流工具，因而更受人才市场青睐，也更有可能适应现有生活环境，攀升到较高的社会地位，其个人社会定位也更为稳定[@ZhangWeiGuoSunTao2016]。

从个体认知来看，语言与塑造自我认知，人们的自我定位很大程度上来源于与他人接触后的内省[@Mead2012]。
个体对于主流语种掌握能力越突出，交流成本越低，在拓展人际网络时遭遇的阻碍越少，其社会融入便顺畅，因而对自身和社会的评价也就越高。 当一个人擅长并非所有人都掌握但又普遍认同某种语言时（如一种通用语），语言就成为证明其能力的依据；语言掌握程度越高，其自我认同也就越强。
譬如，@QiHongLiHong2004 对语言学习者自我认知的研究表明，语言能力的提高对个人自信心具有显著的积极作用。
更进一步，在学习语言的过程中，学习者不仅内化了语言能力，还在与目标文化的交互中完成意义建构或意义生成，从而实现了自我建构和自我评价的提高[@SuFang2020]。
相反，语言掌握程度低会导致使用者的自我评价随之降低。
@WrightTaylor1995 
就基于母语教育对少数民族儿童的学业和心理发展的研究得出，少数民族学生在不熟悉教学语言情况下，极易导致自信水平下降，从而持有更多的消极自我评价。


# 语言治理的实现途径

系统功能类型视角，揭示了语言治理从国家到社会再到个人的纵贯性、多层次的影响。
这些治理影响的实现也存在着具有对应性的三条路径，即阐释政策规范、调整群体关系和改善个体发展环境：

## 阐释政策规范

语言治理在国家层次通过语言政策体现。
语言政策是国家意志在语言政策领域的集中表达，是国家在语言生活领域的治理方案。
语言政策不仅对人们的社会地位认知、社会融入程度，社会参与意愿具有导向作用，还会直接影响民族关系、社会稳定和经济发展。
因此，国家会有目的、有计划、有组织地对语言文字及其使用进行干预与管理，通过立法或者政府调节手段，使语言文字更好地为国家服务[@DaiManChunHeZhanRu2010]。

同时，语言政策作为治理工具，承载着政府对价值取向和治理模式的贯彻，因而治理理念的差异化造就了多样化的语言规划。 如，十月革命后，苏联将大多数语言文字系统改换成拉丁字母文字，包括为少数民族创制拉丁化新文字；越南民主共和国成立后，即宣布拉丁字母的越南文为“国文”，彻底废除了传统社会长期使用的汉文和喃字；北朝鲜独立后，也完全放弃了传统社会长期使用的汉文而改用谚文（即现今的朝鲜文）[@MaRong2004a]。
可见，各国政府努力促进语言政策的本土性转化，在立足具体国情的基础上对语言结构及其使用进行总体规划，以便促进推动本国民族融合、加强国家认同。

不仅如此，传统的政治经济学和族群政治也从政策成本、族群权力、迁移风险等诸多方面探讨过语言规划对族群稳定、经济发展和政策制定的影响，强调语言规划在跨族群社会和国际交往中的作用[@CookLiu2016;@LiuPizzi2018]。
例如，@Liu2015 根据是否为主体民族语言和是否存在多官方语言两个维度，将语言规划分为四类，发现四种语言政策对国内族群互动、国家对外交往、吸引外资均有重要影响。 这类研究也在实践中得到了证实。 非洲新兴独立国家领导人在构建国家认同和民族意识过程中，十分注重语言规划在族群意识、国家身份、经济发展等多个层面对社会成员政治参与的影响[@Laitin1977]。
法国历代政府相继成立诸如法兰西学院、法语和方言总署等有关机构，对法语进行语言规划并大力推广，强硬推行法语，为国家统一性的加强、国族认同度的提高发挥了重要作用[@DaiManChunHeZhanRu2010]。

## 调整群体关系

语言平等是族群平等的重要内容和重要标志之一，国家通过规定各族群使用的词汇和语言，借此改变不同族群的交际行为，以便加强各族群在政治经济和文化情感方面的联系[@KathrynKendall2017]。
一直以来，语言政策作为国家民族政策的重要组成部分，各国政府不断强调语言政策要体现出少数族群的“心理状态”，达到维系民族团结的目的。 
如，1968年美国《双语教育法》的通过便是承认美国语言多元化的事实，承认存在一些母语不是英语的学生（或成人），这一法律的颁布部分地解决了多族群间的语言矛盾和语言冲突，维护了国家和社会的稳定。 
另一个典型例子是瑞士，该国规定国内所有的族群语言都具有平等的法律地位，高中生均要学习三种官方语言（德语、法语、意大利语）[@MengHongLi2010]，这一政策的实施使得瑞士因而被认为只是一个“具有文化差别性的社会”，而非是一个“多数族群－少数族群共存的社会”，从而避免族群差异以任何其他的政治或意识形态出现，实现了多民族社会的稳定团结。

中国的语言制度与民族政策一直面临着西方国家提出的“对少数族群实行同化政策”的舆论批评和外交压力，但中国宪法和相关法令实际上明确规定了各少数族群都有使用和发展其语言文字的自由，中国的语言使用情况也因此呈现出“多元一体”格局。换言之，各个族群都享有保存并发展自己的语言，以维护本民族文化的权利；同时又将汉语作为全国通用的“族际共同语”，以促进各族群间的交流沟通和全国范围内经济、文化等各方面事业的发展。

值得注意的是，过分强调民族语言在国家社会和公共事务中的地位及作用也会在客观导致民族隔绝的非意图后果，致使语言成为某种特殊的族群象征，演变成具有特殊实用意义的工具[@MaRong2017]。
实际上，语言具有文化象征和交流沟通的双重属性。前者带有深厚的历史感与情感色彩，后者则强调语言作为交流与学习的工具性手段。 所以，在政治平等的意义上解决了各族群语言问题的合法性后，必须从应用性角度出发，利用市场经济逐步推动共同语言作为交流工具，打造在经济层面上降低成本、加强合作的政治地理区域。

## 加强个体治理

话语是构建民众世界观和概念化政治问题的一种重要手段。人们的思维依赖于框架、隐喻、意象等语言和认知手段[@Mead2012]，对于同一客观事物，不同的语言表达会产生不同的效果，从而演绎出不同的游戏规则和行事逻辑。因此，国家可以通过控制、筛选、组织和分配话语的生产，借用语言符号来把握微观个体的具体话语行为，潜移默化地加强语言与个体身份的良性构建，从而实现对个体心理的有效引导。
当前，随着新信息技术和电子媒介的出现，政府通常将媒体作为实现言语交际和经验表征的工具，根据政治需要或意识形态的准则来选择、建构和处理新闻话语和图像，以便合法化政府行为。

具体而言，国家通过多模态话语，即语言文字、图像和图表的复合话语来构建社会中的人际互动，利用各种符号模态协同作用共同引导民众心理。
如，@DingJianXinYangHui2020 分析了新冠肺炎爆发时美国媒体如何借用图像、语言来比喻政治，通过在大量新闻标题和政治评论中以“Wuhan Coronavirus”或者“Wuhan Virus”来称呼新冠病毒，甚至出现“黄祸”、“中国病毒”等词，将单纯的医学名词赋予道德批判意义和政治化立场，引导美国民众寻找、建构另一个“他者”，并将罪责归于“他者”，从而加深了美国民众对中国的敌意。

以上三种实现途径构成相互关联、相互影响、有机统一的语言治理体系，对国家稳定、民族团结、个体发展、良好政治秩序的建立和延续，具有长期且深远的影响。

# 语言治理与新时期中国政治发展

当前，我国正处于经济发展方式和社会治理模式的双重变革时期，对国民政治社会心理产生巨大影响，相应一系列问题也随之凸显。
如，由于经济结构剧烈变化而导致的国民自我定位错位[@JingHuaiBinEtAl2017]，由于人口结构变化和加速城镇化带来的人际信任缺失和新老市民身份认同矛盾[@LuHuiLinPanYi2014]，以及人民日益增长的政治参与需求与政府治理方式不匹配等问题[@HaoYuQingCheYue2011]，都成为当代中国社会急需关注的问题。
如处理不当，极易造成民众情绪激化，甚至演变成恶性群体事件，损害社会稳定，威胁正常政治经济秩序。

然而，这些问题的产生很大程度上与语言距离和语言区隔密切相关，语言具有强烈的社会识别功能，对于打破群体隔阂，促进社会公众的心理融合具有重要作用。 上述问题迫切需要国民加快融入主流社会的速度，这就要求其具备较好的沟通能力和较高的语言文字应用水平。 我国语言治理也因此借助以上三种实施途径，呈现出了独特的治理面貌。

## 城市治理

在新时期国家治理与城市治理理念的推动下，城市语言治理能力现代化逐步成为城市研究的新任务。 就时间维度而言，城市语言治理包括常态性问题和应激性问题两部分。
长远看来，如何实现以“人的城镇化”为核心的新型城镇化建设，处理好语言与社会、语言与人际、语言与语言之间的关系，成为当前城市治理和区域发展的新痛点和新难点。

中国城市化进程全面提速，国家统计局最新发布的关于2019年国民经济和社会发展统计公报显示，我国城镇常住人口已达84843万，城镇化率为60.60%，已经超过世界平均水平[@ShenQi2021]。
城镇化的发展促成了频繁的人口流动，导致国内出现了大量的新市民和流动人口。 而无论是农民工还是城市新市民，他们必然带来语言的接触与融合，促使语言地图的变更。 然而，语言地图变更的实质是方言与其他正在逐步逝去的乡土生活和文化记忆共同经历一个前所未有的极速变异过程——亦或是在当地语言之外形成了“方言岛”，亦或是产生了新的语言变体[@WuXiaoJun2020]，而这一过程最终导致了大量人群失语、失权、失利。传统治理视角提出，对于城市主体人群和新进人群/少数人群的隔阂与矛盾，可以通过增强后者的社会融合度（比如农民工的城市化程度或少数民族的融入感等）加以改善。
上述局面的出现使得语言在城市治理中的协调与中介价值更加凸显，现有政府正在通过语言治理促进社会公众心理融合，提升全体公众人际信任和积极心态，为营造和谐社会氛围搭建心理基础，实现普通话、方言和外语和谐共生，助力新型城镇化人本目标的实现。


就当下而言，就应激性问题而言，新冠疫情的爆发暴发使彰显出我国得城市的语言治理能力存在严重不足的问题充分暴露出来[@ShenQi2021]。
2020年上半年，我国大城市疫情防控工作中暴露出一系列涉外语言能力不足以及涉外语言治理空白等问题：国内大城市仍未建设语言人才资源数据库或语言志愿者信息库，导致政府多语信息发布和服务渠道的社会影响力和可及性大打折扣，政府和公共服务机构的语种规划与多语意识亟待全面加强；
不仅如此，城市的语言翻译和语言服务中对外语语种的设置和提供也缺乏深谋远虑，面对大量的在华外国人，尚未形成有效的语言服务协调机制和语言治理体系，各类事务仍然由分散在各政府部门的机构或基层组织自身来解决，缺少有效的合作治理机制，从而严重影响了城市在突发重大事件中的涉外应对能力。

这些问题都提醒我们，我国大城市语言治理能力亟须提升，后疫情时代城市化建设中纷繁复杂的语言治理问题需要更加引起重视，系统探索“自上而下”与“自下而上”双向互动的城市语言治理体系，正当其时。


## 新媒体治理

媒体是现代社会信息的主要提供者，发挥着重要的社会功能。
作为宣传国家语言文字规范标准的重要窗口和践行者，是国家语言规划的关键领域[@ChenLiXiang2021]。
随着人工智能、大数据、云计算、区块链等新一轮新技术的飞速发展，移动应用、社交媒体、网络直播、短视频等新应用、新业态的不断涌现，国内新媒体用户数量的激增和信息传播能力的突显正全方位地重塑媒体格局和社会生态[@TangXuJunEtAl2019]。
依据中国互联网络信息中心（CNNIC）数据，截至2020年3月底，我国网民规模达9.04亿，与2018年底相比增加了7508万；互联网普及率达64.5%，较2018年底提升了4.9个百分点。
我国新媒体的发展出现了井喷态势，根据Statis官网的数据，微信及WeChat活跃用户量在12.03亿以上，抖音及TikTok活跃用户量在8.01亿以上，QQ、新浪微博活跃用户量均在5亿以上[@LiSongLin2021]。
这一新态势和新格局使得媒体的语言文字行为具有范围更广阔的社会示范效应，其巨大的活跃性能也在一定程度上改变着语言文字的生态，给新媒体语言治理带来新的问题。

据此，规范用字用语是我国对新媒体实施语言治理的核心议题。
现有政策主要从社会用字角度，围绕核心议题的“新媒体语言文字使用规范性”来开展，重点规划和解决国家通用语言文字使用、方言使用以及新词新语规范等问题[@ChenLiXiang2021]。
例如，自2001年起实施的《中华人民共和国国家通用语言文字法》是我国第一部语言文字专门法律，成为媒体语言规划相关的地方性法规、行政法规和部门规章的重要参照。
此外，《国家新闻出版广电总局关于规范报刊单位及其所办新媒体采编管理的通知》（2017）、《网络视听节目内容审核通则》（2017）等专门性法律法规均强调“新兴媒体不仅要发挥充分语言的吸引力和传播力，也要发挥语言文字对发展积极向上的网络文化、净化网络环境的重要作用”。
这些具有针对性的语言规划为我国新媒体行业的语言文字使用提供了切实可行的规范。

然而，信息技术的变革使得新媒体的语言影响力正在超越传统媒体，复杂性、动态性、匿名性和开放性等特点使得新媒体在广泛参与社会治理的同时，其自身也成为社会治理的一环[@LiSongLin2021]。 因此，现有以传统媒体为主要治理对象的媒体语言政策，必须更多关注新媒体时代的语言和语言生活，积极统筹各方力量，使政府、社会、公众形成治理共同体，加强各主体之间的督促、衔接和协调，实现媒体语言治理的资源整合和力量融合，构建新媒体治理格局。

## 乡村振兴与共同富裕

2018年9月,中共中央、国务院印发了《乡村振兴战略规划（2018—2022年）》，强调防止因语言能力的缺乏和语言上的弱势致贫返贫，减少语言藩篱对贫困地区发展的束缚，注重语言规划在乡村振兴中的作用。 当前，我国语言治理对乡村振兴的作用主要基于以下两点：

第一，推广普通话对乡村振兴具有促进作用。 通过提高少数民族贫困人口普通话使用能力，搭建沟通桥梁，打破贫困地区和外界信息交流的语言屏障，从而推动贫困地区经济发展[@LiYuMing2018]。
如，通过建立以“普通话专项培训为重点，以其他各类语言文字培训为补充”的教育体系[@TianXueJun2019]，提升乡村地区尤其是民族地区普通民众的基本交际能力和沟通能力，帮助当地居民树立自信心，从而有助于村民内在地改变自身的生活状态和生活面貌。

第二，以振兴乡村文化为要旨，注重多样化语言文化的保护。
通过对少数民族地区当地语言的规划和管理，发掘少数民族语言的本体资源[@SuDe2004;@LiuHuaXiaYuanQingHuan2017]。
如，鼓励和支持各地筹建本地语言文化资源库和语言博物馆、建立地方语言资源平台、举办方言微电影、推动以图、文、音、像、影多种形式全方位展示和利用我国语言方言文化资源，从而形成了推广普通话和保护少数民族语言互促互补的良好局面。

共同富裕是乡村振兴的最终目标，我们必须关注语言如何推动共同富裕的实现。具体而言，我国通过将语言的政治经济和社会文化职能与共同富裕的目标有机结合，推动全社会实现物质生活与精神生活的共同富裕。

首先，以语言技术赋能物质富裕。
作为一种基础性数据，语言文字是数字经济的关键要素之一[@LiYuMing2021a]。
智慧语言教学、智能翻译等技术不仅推动了语言学习和使用方式的变革，而且拓展了语言技术的应用场景和应用深度，，从而促进了语言新业态的产生和数字经济的高速发展，最终夯实了共同富裕的物质基础。

其次，以语言传承推动精神富裕。
中国优秀语言文化的传承创新有助于筑牢中华民族共同体意识，树立文化自觉，增强文化自信[@WangChunHui2020b]。文言文等中华经典诵读、甲骨文等语言资源保护等项目都促使优秀语言文化进一步融入当代语言生活，丰富了当前语言文字所蕴含的精神营养和价值意涵，有助于厚植精神富足、文化浸染的社会土壤。

我们已清晰地认识到了语言的扶贫功能。如，改变贫困人口和贫穷地区的经济劣势和发展劣势。但乡村振兴与共同富裕下的语言治理增添了更多的使命与任务，除了“推普脱贫”彰显其工具性的语言扶贫功能外，仍需不断丰富语言治理的内涵，不断克服语言因素对乡村地区全面发展所产生的阻碍，不断提高内生性的发展能力，推动语言文化的振兴，语言生态的保护，语言资源的开发，做好共同富裕的“语言文章”，真正实现乡村的人才振兴、文化振兴和产业振兴。

# 总结与讨论

本文从语言政治学视角表明语言公共政策对国家治理、群体治理以及个体治理的重要性，揭示出语言影响的长期性、广泛性和复杂性，为我们在较大范围内从事理论概括和理论创新提供了坚实的基础。

本研究归纳了语言治理的三种实施途径，即阐释政策规范、调整族群关系以及加强心理引导。
虽然有关研究已为语言学和教育学学者所关注，但本文从政治学角度出发提供了有关语言治理的实现机制，体现了基于语言功能的不同治理策略，为思考如何切实实现民族平等、有效引导公民参与、降低治理难度提供了新思路。
本研究从城市治理、乡村振兴与共同富裕、新媒体治理三个方面探讨了语言治理与新时期中国政治发展的关系，厘清当前国内语言治理的三个维度，有助于加深对语言政治和语言规划的理解，为制定合理的语言、教育政策提供借鉴，在学术和治理实践上都具有重要启示：

首先，坚持党的领导。
语言治理是一个广泛的社会政治调控过程，其中包含对中国历史、中国国情、中国实践的全面把握，包括对各个国家机关、党政机关的动员组织，是带有全局性、战略性、根本性和长期性的重大任务，只有坚持党中央的集中统一领导，才能有效总揽全局、协调各方，制定正确的语言规划和发展战略，推进中国特色的社会治理、稳定政治秩序，实现语言治理现代化。

其次，服务于国家总体目标。作为国家公共政策的组成部分，国家语言政策的制定及实施应服务于国家治理的总体理念和目标。
习近平总书记指出，要构建集政治安全、国土安全、军事安全、经济安全、文化安全、社会安全、科技安全、信息安全、生态安全、资源安全、核安全等于一体的总体国家安全观。本研究揭示，语言安全不仅是文化安全的重要组成部分，更对政治安全和社会安全具有重要影响。这我们需要更加全面地研究公众语言规划（包括公众外语政策、民族语言政策）对于国家治理的影响，探讨语言规划有效促进国家治理的可能形态，使语言规划更好地为国家总体目标的实现服务，为中华民族共同体和人类命运共同体的建构贡献更多力量。

再次，注重群体身份塑造。语言是最重要的群体属性之一，能够凝聚和强化群体意识，增强群体认同感。
当前，社会分化严重、社会矛盾突出，各群体对公共资源、国家机构，特别是语言规划控制权的争夺日益激烈，极其容易引发群体事件，影响社会秩序稳定。国家治理需要注重语言对群体身份的塑造作用，运用语言治理“润物细无声”的调控功能，对民众心理状态进行潜移默化而又具有持续性的调整和培养，调节个体社会成员的自我定位和人际关系，促进群体间的心理融合，避免话语冲突引起严重的政治冲突。

最后，明确推广普通话的目的和效果。
对于中国这个多方言国家来说，普通话是进行现代国家治理不可或缺的语言工具，但过分推行通用语将会使得方言和少数民族语言式微，导致语言治理效果随之降低，尤其在地方意识或族群文化比较浓厚的地区。不仅如此，目前推广普通话只是聚焦于语音、语调层面的推广[@LuZiWen2008]，国民是否能从语义这个根本目的上理解通用语治理与方言保护之间的非对立性有待考察。这要求我们明确推广普通话的目的和效果，妥善处理推行通用语与保护地方方言、少数民族语言的关系，平衡建立低成本交流环境与合理利用地方文化资源的关系，切实保障语言权利，解决语言问题，构建和谐语言生活。

综上，语言是推进国家治理能力和维护国家安全的重要组成部分和战略支撑力量，锚定语言在国家治理和国家安全中的位置，打造国家治理与国家安全的语言保障体系，维护语言在国家治理与国家安全中的关键要素，是当前时代的应有之义。


# 参考文献 {-}
