---
format: 
  docx:
    reference-doc: template_cn.docx

crossref:
  fig-prefix: "图"
  fig-title: "图"
  tbl-prefix: "表"
  tbl-title: "表"
  eq-title: "公式"
  eq-prefix: "公式"
abstract-title: "摘要"

tables: true # enable longtable and booktabs
fontsize: 12pt
indent: true
geometry: margin=1in
linestretch: 1.5 # double spacing using linestretch 1.5
colorlinks: true
bibliography: [p_language_governance.bib]
biblio-style: apsr
citation_package: natbib
link-citations: true
execute:
  echo: false
  message: false
  warning: false
editor_options: 
  chunk_output_type: console
title: "语言的国家治理意涵与功能研究"
subtitle: "（工作论文，未经作者允许请勿转载或收入论文集）"
author:
  - name: "胡悦"
    institute: "清华大学社会科学学院政治学系"
  - name: "朱萌^[胡悦，清华大学政治学系副教授，博士生导师。**基金项目**：国家自然科学基金面上项目“经济不平等的经济与治理认知塑造机制与行为政策引导策略研究”（编号：72374116）。朱萌，清华大学政治学系博士研究生。]"
    institute: "清华大学社会科学学院政治学系"
abstract: |
  语言是政治运行和政民沟通核心载体。
  然而，对于语言的治理功能和意涵却仍缺乏全面认识。
  本文结合语言政治学前沿理论和实证研究，对语言的治理角色和功能进行了系统阐述，重点探讨语言超越文化和民族事务的治理作用。
  本文提出，语言能够在国家治理、群体治理和个体治理过程中产生多层治理效能，同时通过传递政治意志、调整群体心态和促进个体发展等路径实现其他政策工具罕有的贯通性治理。
  最后，文章针对新型城镇化、意识形态工作和共同富裕三个重点领域，对语言治理效能在具体治理场景中的应用进行了探索性讨论，为如何在新的发展阶段将语言文字工作有机嵌入国家治理体系和治理能力现代化总体目标的实践问题提供思路和视角。
 
  **关键词**：语言治理；国家治理；群体治理；个体治理；系统功能类型学
---

# 引言

语言是政治运行和政民沟通最核心的载体。
政权通过对政治词汇和逻辑的语言解释，阐释治国理念、传达施政方针、表现政治意志；
民众通过接收政府的语言信号，领会政府政治意图、理解治理思路、明确发展方向。
然而，对于语言这一如此根基性的政治生活要素的治理功能和意涵的理解却有待深入。
在政治学领域，既有与语言相关的研究主要聚焦语言在促进国家共同体认同和调整民族关系上的作用[@QuShaoBing2016; @ShiLin2021; @WangChunHui2018]。
从这个角度来看，现代国家对于语言的规范和治理似乎只在建国初期产生作用或仅作用于国家内部的少数族裔和外来人口。
然而，近年来国际学界开始从政治心理和认知塑造角度，重新检视语言在政民互动、意识形态塑造等过程中更具普遍性和长期型的效能 [@Hu2020;@Liu2022; @MartelliJaffrelot2023]。
新研究的不断涌现，促使政治学者重新思考语言在国家治理和政治过程中扮演的角色，也加速了以政治逻辑和视角理解语言公共意涵和治理效能的“语言政治学”逐渐脱离民族政治学和政治修辞学，形成具有独立议题指向和研究方法的新兴交叉学科领域 [@GuoTaiHui2019]。

对于语言国家治理意涵和功能的理解，不仅是一种理论需求，更为探讨如何在新的发展阶段语言文字工作有机嵌入国家治理体系和治理能力现代化总体目标的实践问题提供思路和参考。
2016年，国家语委将国家语言治理写入《国家语言文字事业“十三五”发展规划》，并提出要实现语言治理与国家治理相适应。
2020年10月，第一次全国语言文字会议上提出要“推进语言文字治理体系和治理能力现代化”。
2024年全国语言文字工作会议上，又进一步将语言文字工作与“加快发展新质生产力”绑定。
除了教育、文化传统领域，语言在更广泛公共事务中如何能实现功用，进而促进国家高质量发展，是本文探索的实践之义。

响应理论和实践的双重需求，本文在语言政治学前沿理论和实证研究基础上，对语言在国家治理、群体治理和个体治理三个层面的角色和功能进行了系统阐述，重点探讨语言超越文化和民族事务的治理作用，提出传递政治意志、调整群体心态和促进个体发展三种治理实现路径。
最后，文章针对新型城镇化、意识形态工作和共同富裕三个重点领域，对语言治理效能在具体治理场景中的应用进行了探索性讨论。


# 语言的多层次治理效能

从人类发展角度，语言是人类有别于其他物种的独征（autapomorphy），也是维系人类社会最重要的交际与思维符号体系，个体交流思想与情感的最根本工具 [@BerwickChomsky2016, p. 54]。
从社会政治角度，语言一直以来被认为是凝聚国家共同体意识、承载社会文化身份的重要手段。
社会科学各学科都对语言的社会政治作用有独特视角的阐释：经济学家将语言技能视作一种经济优势，强调语言对个体人力资本的促进作用[@ZhangWeiGuo2011]；
社会语言学家突出语言的个人性与社会性[@LuHuiLinPanYi2014]，侧重语言对个体身份认同的影响；
而政治语言学家更多将语言与国家构建和民族关系相关联[@HeZengKe2014]。
本文承接政治语言学脉络，但侧重从国家功能角度，将语言政策视为一种公共制度手段，从国家全局治理、群体关系治理和个体行为治理的由宏观到微观的层次分析理解语言治理意涵。


## 语言的国家治理功能

语言是国家治理得以实施的基础性条件。
国家治理是国家政权的所有者、管理者和利益相关者等多元行为主体在一国范围内对社会公共事务的合作管理，核心目的在于彰显公共秩序、传达政治意志、实现社会团结。
在这一层面，语言政策和语言治理扮演着影响国家治理有效性和权威性的重要角色。
正如诸多语言政治学研究指出的，语言政策的核心是确定国家官方的统一使用语言以及各种语言类型在国家语言体系中的位置[@Laitin1994; @Pool1991; @Schildkraut2001a]。

官方（使用）语言——通常也是国家通语——具有保证政令可达和提升国家行政效率作用。
因此，推行国家通用语言也成为现代国家普遍采用的语言治理模式[@Liu2015]。
现代国家通用语言的推广，从交流成本层面，有助于消除语言差导致的地域保护主义，推动了共同体的建立，从而维护了国家统一和民族团结 [@ZhangWeiGuo2020]。
一个国家统一时间越长、政府体系越完善，其官方语言的推广范围和使用人群也就越大。
我国自1955年确定推广标准普通话、1956年正式由国务院部署实施，至今已经将近七十年。
当前全国普通话普及率超过80%，预期2025年将达到85% [@ChaiRuJin2022]。


## 语言的群体治理功能

在群体治理层面，语言是跨群体交流的手段，也是群体间得以保持自主性和文化活力的重要倚仗。
群体治理突出民众的自我管理能力，强调在没有政府的参与下，利用群体间的自我协作、社会交往以及非正式协议等自治手段来管理社会团体和社会组织 [@LiuPizzi2018]。
根据社会认同理论，个体通过人际互动塑造群体利益，而语言对于满足人际交往和社会互动的紧迫需求，在更广泛意义上团结松散的民众，形成集体凝聚力具有重要作用。
语言是厘定文化群体边界的核心指标。
人类社会自古以来最简单也是最有效表明自己身份和判断他人身份的手段就是语言 [@WangKeFei2011]。
移民研究也表明，语言是社会融合的前提条件，是正式进入移民社会的必要条件，持有不同语言的移民会遭遇来自主流社会的敌意和排斥，因而由自身母语方言到当地方言的转变被看作是移民文化适应和社会融入的关键标志[@LiangEtAl2018]。

因此，语言对于协调各群体关系具有重要作用。
这一点很多民族关系学者已经有了深入研究[@GuoTaiHui2019; @LiYuMing2008; @MaRong2004]。
同时，文化差异不仅体现在各族群之间，还存在于地域之间。
这种地区性差异，同样可以通过语言，即地方方言，进行标记。
方言是历史和地理因素共同作用的结果，除了文化意义外，也具有极强的地区情感交流和凝聚身份认同功能。

因此，语言的群体治理除了通过推广通用语，调和不同文化和地域背景人群关系外，另一个重要面向是协调通用语与地方语言种类、少数民族语之间的关系。
@HuPizzi2022 的全国调查发现，即使经过了六十多年全国范围内的普通话推广工作，仍有一半以上的本地居民会在工作场合使用本地方言，而工作后生活交流方言使用频率更高。
因此如果仅重视通用语推广，无视地方语言和民族语言的社会政治作用，将会削减地方身份认同，影响地方稳定和社会文化发展。
值得注意的是，新近研究已经表明，不论是地方方言还是少数民族语言，其与通用语的关系都不是相互替代的关系；二者不仅可以共存而且能共同发挥作用 [@HuPizzi2022;@TangHe2010]。
从这一点上，继续推广国家通用语言文字同时，科学保护方言、少数民族语言文字，既具有文化意义，也具有治理意义。


## 语言的个体治理功能

在最微观的个体层面，语言是个体谋求发展的重要社会资本 。
语言作为人类经济活动的工具，在信息传递上具有价值、效用、成本和收益等经济特性。
社会语言学表明，掌握一门语言能够有效提高个体的信息获取能力，进而享有更多的公共资源和发展机会 [@LiYuMing2021a]。
这一点在全国通语上表现得尤为明显。
政治学、经济学和社会学多方向研究表明，相较于其他语言使用者，能熟练使用通用语的社会成员更容易与拥有资源和权力的人建立正向社会关系、展示专业能力，以及学习新技能 [@BerryEtAl1997]。
基于这种语言优势，这类人群通常也会有更多的机会接受更高的教育、获得更好的工作机会、收集到更多的发展信息 [@GodoyEtAl2007; @HanQingLin2006]。
在移民和多种族杂居社会的研究中，通用语的熟练使用者还可能获得更多的经济回报和更多的财务资源来投资于创业、生活质量的改善和个人发展 [@LaitinRamachandran2016]。
在中国的案例研究中，@TangEtAl2016 发现普通话水平是影响人口社会流动和跨民族差异的重要因素。

语言的作用还能触及到个体的社会认知层次。
语言学和神经科学研究表明，人们的自我定位很大程度上来源于与他人接触后的内省，语言在塑造自我认知方面的作用是其他习得能力难以比拟的 [@BerwickChomsky2016]。
其中一种机制来自于社会沟通带来的获得感。
个体语言能力越强，在拓展人际网络时遭遇的阻碍越少，其社会融入便会更加顺畅，因而对自身和社会的评价也就越高 [@QiHongLiHong2004]。
另外，在学习语言的过程中，学习者不仅内化了语言能力，还在与目标文化的交互中完成意义建构和意义生成，从而实现了自我建构和自我评价的提高 [@MaRong2017]。
最后，语言能力的增长也将改变个体获取信息的方式和看待世界的方式，进而影响个体对与政府关系，乃至国际关系的理解 [@HuYueZhuMeng2022;@HuLiu2020]。
通过这些机制，语言影响个体社会经济发展潜质和参与社会政治生活的方式，实现个体层面的治理。


# 语言治理的贯通性治理途径

上文对语言能够产生的治理效能和原理进行了讨论，但这种效能是如何实现的？
本节针对国家、群体、个体三层治理，归纳对应的治理路径，阐释语言是如何贯通宏、中、微观层次，实现治理效果的。

宏观上，传递政治意志。
这一点主要通过国家通用语体现出来。
国家通用语既是一国范围内使用最广泛的语言，也是权威之声。
权威在发布政令、进行宣传以及与公众互动时，采用特定的官方语言，以确保政治意图的传达既统一又精准。
在此过程中，官方语言成为“国家之声”和“政府之音”，与政治权威形成了紧密的认知关联 [@Joseph2006]。
同时，政治权威通过语言政策广泛推行通用语，在最大限度地降低与各类社会群体之间的沟通成本，确保政令能够得到广泛传播。
这一过程促使通用语成为获得公共资源和参与政治活动的必备条件。
通用语与政治权威的结合，共同构建了一个以官方语言为核心的公共语言使用场域。
在这一场域中，社会成员通过通用语可以更有效地获取公共资源、参与政治事务并与政府机构进行沟通。
而国家权威通过以推广通用语为核心的语言行为规范，实现语言在国家层级的治理。

中观上，协调群体心态。
设置地方语言和民族语言在国家语言体系中的位置，往往是国家处理族群关系的重要一环，也是政治语言学研究最主要的探索面向。
前期学者普遍将语言地位与民族地位挂钩，认为调节民族关系的最有效办法是实现不同民族语言在法律和政治层面的平等[详见 @Liu2015 的总结分析]。
但随着政治心理学路径的引入，研究者逐渐发现，语言对群体关系的调节本质是一种集体心理调节，而不一定非要通过给与不同语言同等的政治地位加以实现。
一方面，给与所有民族和地域语言类型同等政治和法律层面的平等本身就是违背治理效率原则的，在现实中无法实现。
另一方面，语言上的阶差并不直接产生群体对立。
比如，@TangHe2010 通过对少数民族的访谈和调查，发现对普通话的学习并未对影响少数民族的族群归属造成影响。
@HuPizzi2022 发现在社会生活中，普通话主要体现沟通功能，而方言则主要承担文化归属功能，二者并存且并不相互替代。
@Hu2020 则通过实验证据表明，普通话使用有利于增强民众对政府代表的信任感，但这不妨碍在日常生活中，民众仍然对和自己使用共同方言的其他个体更加亲近。
因此，只要各种语言的文化价值得到充分认可，通用语和其他语种社会政治生活中各有分工，单一通用语政策同样对群体关系形成正向协调治理作用。

微观上，促进个体发展。
如前所述，在个体层面，语言作为一种社会成本影响个体发展走向。
国家可以通过组织和分配话语的生产，对个体语言能力进行系统性加强，同时也在潜移默化地加强语言与个体身份的良性构建，从而实现对个体心理的有效引导。
这里既包含对于通用语的推广，也包括对于其它语言形式的治理行为，比如通过自上而下倡导方言保护以加强区域内群体认同，以普及外语教育增强民众对外沟通能力和自我能力认知 [@HuYueZhuMeng2022]。
当前，随着新信息技术和电子媒介的出现，政府还可以蒋多种媒体作形式作为实现言语交际和经验表征的工具，根据政治需要或意识形态的准则来选择、建构和处理新闻话语和图像，以便合法化政府行为。

上述三种路径，虽然作用的治理层级不同，但在实践中却具有内在关联性。
宏观层面上的语言治理通过统一和传递政治意志，确保了政策的一致性和权威的稳定性，这是进行群体和个体治理的基础前提。。
中观层面治理通过设定不同语言在国家语言体系中的地位，政府能够在保持国家统一的同时，认可和尊重多样性。
这种群体层面的语言政策既是对宏观语言治理的补充，也是为微观层面的个体互动提供了文化和社会的背景。
最后，在微观层面，语言治理直接影响到个体的发展和身份构建，通过提高个体的语言能力，使他们能更有效地参与社会和政治生活，从而实现个体与群体之间的和谐。
三种治理路径相互关联，共同作用，形成了一个从宏观到微观的治理连续体。
宏观的政策为中观的族群关系和微观的个体发展提供了方向和环境，而中观和微观层面的实践又反馈并影响宏观政策的调整和完善。
通过这种多层次的互动，语言成为连接政府与民众、传统与现代、全局与个体的桥梁，有效地促进了社会的整体治理和发展。

# 语言治理在新时期国家治理体系中的应用场景

语言治理具有其他治理共举少有的多层次效能和贯通性路径，但只有与具体的治理场景相结合，才能更深刻地理解其对于推动国家治理体系和治理能力现代化的实际意义。
当前，我国正处于经济发展方式和社会治理模式的双重变革时期，对国民政治社会心理产生巨大影响，相应一系列问题也随之凸显。
如由于经济结构剧烈变化而导致的国民自我定位错位，由于人口结构变化和加速城镇化带来的人际信任缺失和新老市民身份认同矛盾，由于人民日益增长的政治参与需求与政府治理方式不匹配所导致的参与失序，都成为当代中国社会急需解决的问题[@WuXiaoJun2020]。
如处理不当，极易造成民众情绪激化，甚至演变成恶性群体事件，损害社会稳定，威胁正常的政治经济秩序。
妥善使用语言治理手段将为治理主体解决这些现实问题提供助力。


## 语言治理与新型城镇化

语言融合问题向来与城镇化研究相伴而生。
大量针对进城务工人员的研究，都指向了语言方向[@WuXiaoJun2015;@ChuRongWeiEtAl2014; @FangYan2015; @LiHongYangLiYuan2015; @LiuGuoHuiZhangWeiGuo2020; @YuWeiQi2017]。
这些研究指出，城镇化的飞速发展带来了大量进城务工人员和新市民，伴随着人口流动带来的语言接触和融合，造成了语言地图的剧烈变更。
在沟通层面，由于普通话的大范围普及，语言地图变更对外来人员的沟通影响正在逐步降低，但方言及其所蕴含的文化记忆极速变异却造成了对本地人和新市民共同的身份认同缺失问题。

以往的研究多强调通过加强个体普通话和当地方言能力方式，增强其对本地社会经济生活的融入。
这是一种在个体层面的治理方式，确实能从个体发展角度改善一些问题。
然而，面对身份问题，则需要从群体和国家层面进行考量，站在重塑新时代新市民身份高度思考问题解法。
在这方面，推广本地方言学习项目将是推动新市民了解本地文化，动员老市民接纳新市民的一种尝试。
现在部分地区出现的基于本地方言的脱口秀、流行歌曲就是这种群体学习和融入的体现，值得作为社会治理模式进行系统观察和试点实践。

## 语言治理与意识形态工作

语言是意识形态工作的天然载体。
传统意义上的意识形态工作多指文字层面的规范、界定、引导工作。
但随着人工智能等新一轮新技术的飞速发展，以多模态信息传输为特征的新媒体使用迅速普及，用户数量的激增和信息传播能力的突显正全方位地重塑媒体格局和社会生态[@ChenLiXiang2021]。
这一新态势和新格局使得政府信息和行为具有更广阔的社会示范效应，但也对意识形态工作形成挑战。

规范新媒体实施语言将是新时期语言治理的核心议题。
一方面，这将是在国家层级的系统性工程，但另一方面也是细致到个体表达的微观任务。
新时期语言政策需要在张弛有度的前提下，从社会用语规范角度对新媒体语言的声音、文字、形态表达进行疏导和规范。
同时，在群体层面，需要将新媒体平台视为社会治理的共同参与者，纳入治理过程，以形成自上而下的规划引导加自下而上的行为自觉的上下配合治理格局，统筹各方力量，使政府、社会、公众形成治理合力。

## 语言治理与共同富裕

对语言与经济关系一直是政治语言学一个重点研究面向，但研究核心议题是如何通过增强语言能力加强个体发展可能，帮助其脱离贫困 [@WangChunHui2019;@LaitinRamachandran2016]。
然而，不论是中国农村发展还是城镇化都进入了新阶段。
新阶段的乡村振兴覆盖区域更广、时间跨度更长、目标维度更全，它不再只是从经济层面解决农民的贫困问题，而是一次以人才振兴为抓手促进产业振兴、组织振兴、文化振兴和生态振兴的系统性建设，通过将语言的政治经济和社会文化职能与共同富裕的目标有机结合，实现全社会实现物质生活与精神生活的共同富裕。
在新阶段，如果治理主体仍然只关注语言对基础个体发展能力的作用，如在“推普脱贫攻坚”中的角色，那么其治理能力发挥将是非常有限的。
基于语言治理的贯通性，至少有三个方向能使语言治理发挥更大的效能：

首先，将语言资源转化为发展资源。
治理主体需要转变对语言治理效能的单一认识，在继续克服语言因素对乡村地区全面发展所产生的阻碍同时，推动乡村地区语言文化的振兴，进行语言生态的良性保护和语言资源的有效开发，将方言文化转化为经济添加剂和社会稳定剂，实现乡村的文化振兴和产业振兴，做好共同富裕的“语言文章”。

第二，以语言传承推动精神富裕。
中国优秀语言文化的传承创新有助于筑牢中华民族共同体意识，树立文化自觉，增强文化自信。
在语言政策制定中兼具宣传教育和审美功能，促使优秀语言文化进一步融入当代语言生活，丰富当前语言文字所蕴含的精神营养和价值意涵，从而培养精神富足和文化浸染的社会土壤。

最后，以语言技术赋能物质富裕。
作为一种基础性数据，语言文字是数字经济的关键要素之一。
智慧语言教学等技术的兴起增强了村民的语言传播能力和语言信息处理能力。
各地政府通过筹建本地语言文化资源库和语言博物馆、建立地方语言资源平台，拓展了语言技术的应用场景和应用深度，从而促进了语言新业态的产生和数字经济的高速发展，实现了将语言能力的提升与村民的全面发展相结合，最终夯实了共同富裕的物质基础。


# 总结与讨论

本文从语言政治语言学视角，结合学科发展前沿成果，阐述语言在国家治理体系中扮演的国家、群体、个体多层治理效能，并揭示了通过语言治理实现治理贯通性的三种途径。
最后文章讨论在三个具体的治理场景中，语言治理的可应用方向和预期效果。
对于语言的治理意涵，虽然已有社会语言学和教育学学者有所关注，但本文从政治学视角出发，提供了对语言的治理效能和机制的系统认识，体现了基于语言功能的不同治理策略，为思考如何切实实现民族平等、有效引导公民参与、降低治理难度提供了新思路。
本文将语言面向在推进国家治理体系和治理能力现代化的情境中进行研究，提供了新的视角来审视如权力动态、公共政策及公民与国家的关系等传统的政治科学议题，力图将认知和心理学的洞见融入到对语言治理意涵的理解中，更系统展现了细致入微的语言管理策略可以帮助缓解冲突、促进社会凝聚力，并增强政府权威的合法性。
随着我们继续在复杂的社会和政治环境中前行，战略性的语言治理将在维持稳定和促进包容性发展中扮演关键角色。

对于结合治理场景的讨论探索了语言治理与新时期中国政治发展的关系，丰富了语言治理在新时期国家治理体系中的应用场景，有助于加深对语言政治和语言规划的理解，为制定合理的语言政策和教育政策提供借鉴，在学术和治理实践上都具有重要启示：

首先，服务于国家总体目标。
作为国家公共政策的组成部分，国家语言政策的制定及实施应服务于国家治理的总体理念和目标。
这需要更加全面地研究公众语言规划对于国家治理的影响，探讨语言政策有效促进国家治理的可能形态，使语言规划更好地为国家总体目标的实现服务，为铸就中华民族共同体和人类命运共同体贡献更多力量。

其次，注重群体心理塑造。
当前，社会分化严重、社会矛盾突出，各群体对公共资源、国家机构，特别是语言规划控制权的争夺日益激烈，极其容易引发群体事件，影响社会秩序稳定。
国家治理需要注重语言对群体身份的塑造作用，运用语言治理“润物细无声”的调控功能，对民众心理状态进行潜移默化而又具有持续性的调整和培养，调节个体社会成员的自我定位和人际关系，促进群体间的心理融合，避免话语冲突引起严重的政治冲突。

最后，明确推广普通话的治理目的和效果。
对于中国这个多方言国家来说，普通话是进行现代国家治理不可或缺的语言工具，但过分推行通用语将会使得方言和少数民族语言式微，导致语言治理效果随之降低。
这要求我们明确推广普通话的目的和效果，妥善处理推行通用语与保护地方方言、少数民族语言的关系，平衡建立低成本交流环境与合理利用地方文化资源的关系，切实保障语言权利，解决语言问题，构建和谐语言生活。

# 参考文献 {-}
